export interface GameTheme {
  id: string;
  name: string;
  description: string;
  icon: string;
  status: 'Play Now' | 'Coming Soon';
  symbols: string[]; // Ordered from most common to rarest
  payouts: { [symbol: string]: { [count: number]: number } };
  bonusSymbol: string;
  freeSpinsRewards: { [count: number]: number };
}

// Helper to generate payouts based on symbol order
const generatePayouts = (symbols: string[]): { [symbol: string]: { [count: number]: number } } => {
  const payouts: { [symbol: string]: { [count: number]: number } } = {};
  const basePayouts = [2, 5, 8, 10, 15, 20, 30, 50, 75, 100, 250]; // Base values for 3-of-a-kind

  symbols.forEach((symbol, index) => {
    const base = basePayouts[index] || basePayouts[basePayouts.length - 1];
    payouts[symbol] = {
      3: base,
      4: base * 2,
      5: base * 5,
    };
  });
  return payouts;
};

const createTheme = (data: Omit<GameTheme, 'payouts' | 'freeSpinsRewards'> & { freeSpinsRewards?: { [count: number]: number } }): GameTheme => {
  return {
    ...data,
    payouts: generatePayouts(data.symbols),
    freeSpinsRewards: data.freeSpinsRewards || { 3: 5, 4: 10, 5: 25 },
  };
};

export const gameThemes: GameTheme[] = [
  createTheme({
    id: 'markkd_bills',
    name: 'MARKK’D BILLS',
    description: 'Stack the bills, swipe the cards, spin the coins. If you hit the Currency Exchange, the whole game flips into free-spin frenzy.',
    icon: '💵',
    status: 'Play Now',
    symbols: ['🏧', '🏦', '🧾', '🪙', '💳', '💸', '💷', '💶', '💴', '💵'],
    bonusSymbol: '💱',
  }),
  createTheme({
    id: 'fruit_frenzy',
    name: 'FRUIT FRENZY',
    description: 'A juicy twist on a classic favorite. Line up the fruits for a sweet, sweet payout.',
    icon: '🍓',
    status: 'Play Now',
    symbols: ['🍒', '🍋', '🍊', '🍇', '🍉', '🥝', '🍍', '🍓'],
    bonusSymbol: '⭐',
  }),
  createTheme({
    id: 'veggie_village',
    name: 'VEGGIE VILLAGE',
    description: 'It\'s harvest time! Spin the reels and gather the freshest veggies for a healthy win.',
    icon: '🥕',
    status: 'Play Now',
    symbols: ['🌽', '🍆', '🍅', '🥬', '🥦', '🌶️', '🥕', '🥔'],
    bonusSymbol: '🏆',
  }),
  createTheme({
    id: 'ocean_odds',
    name: 'OCEAN ODDS',
    description: 'Dive deep for treasures untold. Match the sea creatures to reel in a legendary catch.',
    icon: '🐠',
    status: 'Play Now',
    symbols: ['🐡', '🐙', '🦀', '🦞', '🐬', '🐳', '🐢', '🐠'],
    bonusSymbol: '💎',
  }),
  createTheme({
    id: 'cosmic_credits',
    name: 'COSMIC CREDITS',
    description: 'Blast off into a galaxy of winnings! Align the planets and stars for an astronomical reward.',
    icon: '🪐',
    status: 'Play Now',
    symbols: ['🌕', '⭐', '☄️', '🌍', '👽', '🚀', '🔭', '🪐'],
    bonusSymbol: '🌌',
  }),
  createTheme({
    id: 'jungle_jackpots',
    name: 'JUNGLE JACKPOTS',
    description: 'The jungle is calling! Swing through the vines and uncover wild treasures.',
    icon: '🐒',
    status: 'Play Now',
    symbols: ['🐍', '🦜', '🐸', '🐅', '🦁', '🐘', '🦍', '🐒'],
    bonusSymbol: '👑',
  }),
  createTheme({
    id: 'dessert_dollars',
    name: 'DESSERT DOLLARS',
    description: 'Satisfy your sweet tooth and your wallet! A delicious spin for delectable prizes.',
    icon: '🍰',
    status: 'Play Now',
    symbols: ['🍪', '🍩', '🍨', '🍦', '🍮', '🍭', '🎂', '🍰'],
    bonusSymbol: '🎁',
  }),
  createTheme({
    id: 'farm_fortunes',
    name: 'FARM FORTUNES',
    description: 'Old MacDonald had a farm, and on that farm he had some slots!',
    icon: '🐔',
    status: 'Play Now',
    symbols: ['🐑', '🐖', '🐄', '🐎', '🐕', '🐓', '🚜', '🐔'],
    bonusSymbol: '🏡',
  }),
   createTheme({
    id: 'gem_getaway',
    name: 'GEM GETAWAY',
    description: 'Unearth a fortune in sparkling jewels. A dazzling game for brilliant wins.',
    icon: '💎',
    status: 'Play Now',
    symbols: ['⚪', '🟡', '🟠', '🔴', '🟣', '🔵', '🟢', '💎'],
    bonusSymbol: '💍',
  }),
  createTheme({
    id: 'fast_food_fever',
    name: 'FAST FOOD FEVER',
    description: 'Order up a combo of wins! A tasty game with a side of jackpot.',
    icon: '🍔',
    status: 'Play Now',
    symbols: ['🍿', '🥤', '🌭', '🍕', '🍟', '🌮', '🍗', '🍔'],
    bonusSymbol: '⭐',
  }),
  // --- COINS SYSTEM GAMES ---
  createTheme({
    id: 'fruit_frenzy_coins',
    name: 'FRUIT FRENZY COINS',
    description: 'A classic fruity mix with a coin-powered twist. Spin for a sweet and juicy payout!',
    icon: '🍍',
    status: 'Play Now',
    symbols: ['🍒', '🍌', '🍇', '🍎', '🍉', '🍍'],
    bonusSymbol: '⭐',
  }),
  createTheme({
    id: 'veggie_coin_craze',
    name: 'VEGGIE COIN CRAZE',
    description: 'The harvest is here! A healthy spin for a wealthy win in this garden of green.',
    icon: '🥕',
    status: 'Play Now',
    symbols: ['🥒', '🌽', '🍆', '🥦', '🥕'],
    bonusSymbol: '🏆',
  }),
  createTheme({
    id: 'coin_cascade_colors',
    name: 'COIN CASCADE COLORS',
    description: 'Paint the reels with winning combinations. A colorful adventure for a golden prize.',
    icon: '🟥',
    status: 'Play Now',
    symbols: ['🟦', '🟩', '🟨', '🟧', '🟥'],
    bonusSymbol: '🌈',
  }),
  createTheme({
    id: 'shape_coin_shuffle',
    name: 'SHAPE COIN SHUFFLE',
    description: 'Line up the shapes and watch your fortune take form. A geometric path to riches.',
    icon: '🔷',
    status: 'Play Now',
    symbols: ['⚫', '⚪', '🔻', '🔺', '🔶', '🔷'],
    bonusSymbol: '⭐',
  }),
  createTheme({
    id: 'coin_letter_loot',
    name: 'COIN LETTER LOOT',
    description: 'Spell out your victory! Every letter brings you closer to the jackpot.',
    icon: '🇦',
    status: 'Play Now',
    symbols: ['🇫', '🇪', '🇩', '🇨', '🇧', '🇦'],
    bonusSymbol: '💯',
  }),
  createTheme({
    id: 'coin_number_nuggets',
    name: 'COIN NUMBER NUGGETS',
    description: 'Count your winnings! These numbers add up to big coin payouts.',
    icon: '4️⃣',
    status: 'Play Now',
    symbols: ['0️⃣', '1️⃣', '2️⃣', '3️⃣', '4️⃣'],
    bonusSymbol: '🔟',
  }),
  createTheme({
    id: 'coin_food_fortune',
    name: 'COIN FOOD FORTUNE',
    description: 'A feast of fortune awaits. Order up a winning combo for a delicious payout.',
    icon: '🍔',
    status: 'Play Now',
    symbols: ['🍟', '🌭', '🍣', '🍕', '🍔'],
    bonusSymbol: '⭐',
  }),
  createTheme({
    id: 'dessert_coin_delight',
    name: 'DESSERT COIN DELIGHT',
    description: 'Sweet wins and sugary spins! A delectable journey for delightful prizes.',
    icon: '🍰',
    status: 'Play Now',
    symbols: ['🍮', '🍨', '🍦', '🧁', '🍰'],
    bonusSymbol: '🎁',
  }),
  createTheme({
    id: 'animal_coin_ambush',
    name: 'ANIMAL COIN AMBUSH',
    description: 'The wild is calling! Let the animal kingdom guide you to a roaring win.',
    icon: '🐻',
    status: 'Play Now',
    symbols: ['🐭', '🐱', '🐶', '🐰', '🐻'],
    bonusSymbol: '🐾',
  }),
  createTheme({
    id: 'ocean_coin_rush',
    name: 'OCEAN COIN RUSH',
    description: 'Dive into deep waters and discover a treasure trove of coins.',
    icon: '🐳',
    status: 'Play Now',
    symbols: ['🐠', '🐟', '🦀', '🐬', '🐳'],
    bonusSymbol: '💎',
  }),
  createTheme({
    id: 'coin_weather_wins',
    name: 'COIN WEATHER WINS',
    description: 'Forecast: a storm of coins! Brave the elements for a whirlwind of winnings.',
    icon: '🌈',
    status: 'Play Now',
    symbols: ['🌧️', '🌨️', '⛈️', '🌞', '🌈'],
    bonusSymbol: '🌀',
  }),
  createTheme({
    id: 'coin_space_spins',
    name: 'COIN SPACE SPINS',
    description: 'An interstellar adventure for astronomical rewards. The galaxy is full of coins!',
    icon: '🪐',
    status: 'Play Now',
    symbols: ['🌙', '⭐', '💫', '🚀', '🪐'],
    bonusSymbol: '🌌',
  }),
  createTheme({
    id: 'coin_treasure_trail',
    name: 'COIN TREASURE TRAIL',
    description: 'Follow the map to buried treasure. X marks the slot!',
    icon: '💎',
    status: 'Play Now',
    symbols: ['🪙', '💰', '🏆', '💎'],
    bonusSymbol: '🗺️',
  }),
  createTheme({
    id: 'coin_holiday_havoc',
    name: 'COIN HOLIDAY HAVOC',
    description: 'Celebrate the seasons with festive wins. Every holiday brings a new chance for coins.',
    icon: '🎄',
    status: 'Play Now',
    symbols: ['🦃', '🎃', '🎆', '🎄'],
    bonusSymbol: '🎁',
  }),
  createTheme({
    id: 'transport_coin_triumph',
    name: 'TRANSPORT COIN TRIUMPH',
    description: 'Planes, trains, and automobiles... and coins! Race your way to the finish line.',
    icon: '✈️',
    status: 'Play Now',
    symbols: ['🚗', '🚕', '🛻', '✈️'],
    bonusSymbol: '🏁',
  }),
  createTheme({
    id: 'jungle_coin_jackpot',
    name: 'JUNGLE COIN JACKPOT',
    description: 'Swing through the vines and uncover ancient coins in this jungle adventure.',
    icon: '🐒',
    status: 'Play Now',
    symbols: ['🌴', '🦜', '🐅', '🦁', '🐒'],
    bonusSymbol: '👑',
  }),
  createTheme({
    id: 'gemstone_coin_storm',
    name: 'GEMSTONE COIN STORM',
    description: 'A glittering cascade of jewels and coins. Dazzling spins for brilliant wins.',
    icon: '💎',
    status: 'Play Now',
    symbols: ['🟪', '🔶', '🔷', '💎'],
    bonusSymbol: '💍',
  }),
  createTheme({
    id: 'lucky_coin_charms',
    name: 'LUCKY COIN CHARMS',
    description: 'Find your lucky charm and let fortune smile upon you. A magical spin for enchanted coins.',
    icon: '🍀',
    status: 'Play Now',
    symbols: ['🐞', '💫', '🌈', '🍀'],
    bonusSymbol: '⭐',
  }),
  createTheme({
    id: 'mythic_coin_masters',
    name: 'MYTHIC COIN MASTERS',
    description: 'Unleash legendary beasts and claim mythical treasures. A heroic quest for coins.',
    icon: '🐲',
    status: 'Play Now',
    symbols: ['⚔️', '👑', '🦄', '🐲'],
    bonusSymbol: '📜',
  }),
  createTheme({
    id: 'retro_coin_reels',
    name: 'RETRO COIN REELS',
    description: 'A blast from the past! Spin the reels for a nostalgic win in this 8-bit adventure.',
    icon: '🕹️',
    status: 'Play Now',
    symbols: ['📟', '💾', '📼', '🕹️'],
    bonusSymbol: '👾',
  }),
  createTheme({
    id: 'candy_coin_carnival',
    name: 'CANDY COIN CARNIVAL',
    description: 'Welcome to the sweetest show on earth! A carnival of candy and coins awaits.',
    icon: '🍭',
    status: 'Play Now',
    symbols: ['🍡', '🍬', '🍫', '🍭'],
    bonusSymbol: '🎟️',
  }),
  createTheme({
    id: 'safari_coin_spins',
    name: 'SAFARI COIN SPINS',
    description: 'Go on a wild safari and spot the winning combinations. An untamed adventure for coins.',
    icon: '🐘',
    status: 'Play Now',
    symbols: ['🦓', '🐆', '🦒', '🐘'],
    bonusSymbol: '🔭',
  }),
  createTheme({
    id: 'casino_coin_craze',
    name: 'CASINO COIN CRAZE',
    description: 'All the glitz and glamour of the casino floor. Go all in for a royal flush of coins.',
    icon: '🎲',
    status: 'Play Now',
    symbols: ['♣️', '♦️', '♥️', '♠️', '🎲'],
    bonusSymbol: '🃏',
  }),
  createTheme({
    id: 'robot_coin_factory',
    name: 'ROBOT COIN FACTORY',
    description: 'Enter the factory where coins are made. A futuristic spin for a robotic reward.',
    icon: '🤖',
    status: 'Play Now',
    symbols: ['⚙️', '🔋', '💽', '🤖'],
    bonusSymbol: '⚡',
  }),
  createTheme({
    id: 'coin_fire_frenzy',
    name: 'COIN FIRE FRENZY',
    description: 'Things are heating up! A scorching hot game for fiery wins.',
    icon: '🔥',
    status: 'Play Now',
    symbols: ['🕯️', '🌶️', '☀️', '🔥'],
    bonusSymbol: '🌋',
  }),
  // --- KASH SYSTEM GAMES ---
  createTheme({
    id: 'kash_fruit_kingdom',
    name: 'KASH FRUIT KINGDOM',
    description: 'Rule the reels in this kingdom of fruity kash. A royal harvest awaits.',
    icon: '🍉',
    status: 'Play Now',
    symbols: ['🥭', '🍓', '🍍', '🍉'],
    bonusSymbol: '👑',
  }),
  createTheme({
    id: 'veggie_kash_vault',
    name: 'VEGGIE KASH VAULT',
    description: 'Unlock the vault to a garden of green kash. A healthy payout for a wealthy player.',
    icon: '🥦',
    status: 'Play Now',
    symbols: ['🧅', '🍄', '🥬', '🥦'],
    bonusSymbol: '🏦',
  }),
  createTheme({
    id: 'color_kash_clash',
    name: 'COLOR KASH CLASH',
    description: 'A vibrant battle for kash! May the most colorful combination win.',
    icon: '🟪',
    status: 'Play Now',
    symbols: ['🟩', '🟦', '🟥', '🟪'],
    bonusSymbol: '💥',
  }),
  createTheme({
    id: 'shape_kash_spinout',
    name: 'SHAPE KASH SPINOUT',
    description: 'Get in shape for a big win! A geometric game with sharp payouts.',
    icon: '🔷',
    status: 'Play Now',
    symbols: ['⬜', '⬛', '🔺', '🔷'],
    bonusSymbol: '💫',
  }),
  createTheme({
    id: 'kash_letter_kings',
    name: 'KASH LETTER KINGS',
    description: 'Become the king of the alphabet and spell your way to a royal kash prize.',
    icon: '🇦',
    status: 'Play Now',
    symbols: ['🇪', '🇩', '🇨', '🇧', '🇦'],
    bonusSymbol: '👑',
  }),
  createTheme({
    id: 'kash_number_rush',
    name: 'KASH NUMBER RUSH',
    description: 'A high-stakes number game. The bigger the number, the bigger the kash.',
    icon: '9️⃣',
    status: 'Play Now',
    symbols: ['5️⃣', '6️⃣', '7️⃣', '8️⃣', '9️⃣'],
    bonusSymbol: '💯',
  }),
  createTheme({
    id: 'kash_food_jackpot',
    name: 'KASH FOOD JACKPOT',
    description: 'A culinary competition for kash! Cook up a winning dish for a tasty reward.',
    icon: '🍗',
    status: 'Play Now',
    symbols: ['🍛', '🍜', '🍣', '🍗'],
    bonusSymbol: '🏆',
  }),
  createTheme({
    id: 'kash_dessert_drop',
    name: 'KASH DESSERT DROP',
    description: 'A sweet drop of kash is waiting. A delicious game with a rich payout.',
    icon: '🍩',
    status: 'Play Now',
    symbols: ['🍮', '🍧', '🍩'],
    bonusSymbol: '💰',
  }),
  createTheme({
    id: 'kash_animal_attack',
    name: 'KASH ANIMAL ATTACK',
    description: 'A ferocious battle for kash! Let the alpha animal lead you to victory.',
    icon: '🐻‍❄️',
    status: 'Play Now',
    symbols: ['🦊', '🐺', '🐗', '🐻‍❄️'],
    bonusSymbol: '💥',
  }),
  createTheme({
    id: 'ocean_kash_overtime',
    name: 'OCEAN KASH OVERTIME',
    description: 'The pressure is on in the deep sea. Hunt for the predator\'s kash.',
    icon: '🦈',
    status: 'Play Now',
    symbols: ['🐚', '🌊', '🐙', '🦈'],
    bonusSymbol: '🏴‍☠️',
  }),
  createTheme({
    id: 'kash_weather_wave',
    name: 'KASH WEATHER WAVE',
    description: 'Ride the wave of kash in this stormy sea of slots.',
    icon: '🌪️',
    status: 'Play Now',
    symbols: ['⛅', '🌨️', '☀️', '🌪️'],
    bonusSymbol: '🌊',
  }),
  createTheme({
    id: 'kash_galaxy_gains',
    name: 'KASH GALAXY GAINS',
    description: 'Explore the final frontier of kash. A cosmic quest for stellar wins.',
    icon: '🌌',
    status: 'Play Now',
    symbols: ['🌟', '🛸', '🪐', '🌌'],
    bonusSymbol: '💰',
  }),
  createTheme({
    id: 'kash_treasure_takedown',
    name: 'KASH TREASURE TAKEDOWN',
    description: 'A high-stakes heist for hidden kash. Break the bank to win.',
    icon: '💰',
    status: 'Play Now',
    symbols: ['🪙', '🧿', '🗝️', '💰'],
    bonusSymbol: '💥',
  }),
  createTheme({
    id: 'kash_holiday_hits',
    name: 'KASH HOLIDAY HITS',
    description: 'The holidays are here, and so is the kash! A festive celebration of big wins.',
    icon: '🎁',
    status: 'Play Now',
    symbols: ['🎉', '🕎', '🎁'],
    bonusSymbol: '🎊',
  }),
  createTheme({
    id: 'kash_transport_turbo',
    name: 'KASH TRANSPORT TURBO',
    description: 'Put the pedal to the metal for a high-speed kash prize.',
    icon: '✈️',
    status: 'Play Now',
    symbols: ['🚤', '🚂', '🚁', '✈️'],
    bonusSymbol: '🚀',
  }),
  createTheme({
    id: 'kash_dragon_riches',
    name: 'KASH DRAGON RICHES',
    description: 'Face the dragon and claim its hoard of kash. A fiery challenge for a legendary reward.',
    icon: '🐉',
    status: 'Play Now',
    symbols: ['💴', '🔥', '🐉'],
    bonusSymbol: '💰',
  }),
  createTheme({
    id: 'kash_neon_nights',
    name: 'KASH NEON NIGHTS',
    description: 'The city that never sleeps, and the kash that never stops. A bright lights, big win adventure.',
    icon: '🌃',
    status: 'Play Now',
    symbols: ['🪩', '🎆', '🌃'],
    bonusSymbol: '✨',
  }),
  createTheme({
    id: 'kash_comic_chaos',
    name: 'KASH COMIC CHAOS',
    description: 'A superhero showdown for kash! Save the day and win the jackpot.',
    icon: '💥',
    status: 'Play Now',
    symbols: ['🌀', '⭐', '💥'],
    bonusSymbol: '🦸',
  }),
  createTheme({
    id: 'kash_farm_frenzy',
    name: 'KASH FARM FRENZY',
    description: 'A bumper crop of kash is ready for harvest. A down-to-earth game with big payouts.',
    icon: '🐄',
    status: 'Play Now',
    symbols: ['🌾', '🐑', '🐓', '🐄'],
    bonusSymbol: '🚜',
  }),
  createTheme({
    id: 'kash_mega_music',
    name: 'KASH MEGA MUSIC',
    description: 'Hit the right notes and rock your way to a chart-topping kash prize.',
    icon: '🎸',
    status: 'Play Now',
    symbols: ['🎵', '🎶', '🎤', '🎸'],
    bonusSymbol: '⭐',
  }),
  createTheme({
    id: 'kash_royal_wins',
    name: 'KASH ROYAL WINS',
    description: 'A game of thrones for a king\'s ransom. Claim your crown and your kash.',
    icon: '👑',
    status: 'Play Now',
    symbols: ['💷', '💼', '👑'],
    bonusSymbol: '💎',
  }),
  createTheme({
    id: 'kash_galaxy_million',
    name: 'KASH GALAXY MILLION',
    description: 'A million-dollar mission to the stars. Your fortune is written in the cosmos.',
    icon: '🚀',
    status: 'Play Now',
    symbols: ['💫', '🪐', '🚀'],
    bonusSymbol: '🌌',
  }),
  createTheme({
    id: 'kash_pirate_plunder',
    name: 'KASH PIRATE PLUNDER',
    description: 'Ahoy, matey! Sail the seven seas in search of buried kash.',
    icon: '🏴‍☠️',
    status: 'Play Now',
    symbols: ['🪙', '⚓', '🏴‍☠️'],
    bonusSymbol: '💎',
  }),
  createTheme({
    id: 'kash_crystal_kings',
    name: 'KASH CRYSTAL KINGS',
    description: 'The crystal caves hold a kingly fortune. A magical quest for glittering kash.',
    icon: '💎',
    status: 'Play Now',
    symbols: ['✨', '🔮', '💎'],
    bonusSymbol: '👑',
  }),
  createTheme({
    id: 'kash_fortune_falls',
    name: 'KASH FORTUNE FALLS',
    description: 'Let the kash rain down! A waterfall of wealth awaits the lucky spinner.',
    icon: '💵',
    status: 'Play Now',
    symbols: ['💸', '⛲', '💵'],
    bonusSymbol: '💰',
  }),
  // --- COMING SOON ---
  createTheme({
    id: 'weather_winnings',
    name: 'WEATHER WINNINGS',
    description: 'Forecast: a storm of coins! Brave the elements and predict a winning combination.',
    icon: '⚡',
    status: 'Coming Soon',
    symbols: ['💧', '💨', '☀️', '☁️', '❄️', '🌈', '🌪️', '⚡'],
    bonusSymbol: '🌀',
  }),
  createTheme({
    id: 'sports_slots',
    name: 'SPORTS SLOTS',
    description: 'Go for the gold! Line up your favorite sports for a championship-level prize.',
    icon: '⚽',
    status: 'Coming Soon',
    symbols: ['⚾', '🏀', '🏈', '🎾', '🎳', '🥇', '🏆', '⚽'],
    bonusSymbol: '🏁',
  }),
];

export const themesById = new Map(gameThemes.map(theme => [theme.id, theme]));
